#!/bin/bash

# Usage: git-diff-grep <revs-number> <query>

# Example: "git-diff-grep 10 login_required" will grep for
# login_required in the last 10 commits diffs

git log --pretty=oneline -$1 | awk '{print $1}' |
while read rev; do
  git diff $rev |

  grep -q "$2"
  if [ $? -eq 0 ]
  then
    echo "  commit $rev"
    git show -s --format="  Author: %cn <%cE>" $rev
    git show -s --format="  Date: %cd" $rev
    git show -s --format="    %s" $rev
    echo
    git diff $rev | grep "$2"
    echo
    echo
  fi

done

